language: java

jdk:
  - oraclejdk8
  
before_install:
  - pip install --user codecov

script: mvn clean compile test cobertura:cobertura

after_success:
  - codecov

cache:
  directories:
  - $HOME/.m2