language: java

jdk:
  - oraclejdk8
  
before_install:
  - pip install --user codecov
  - distribution/prepare.sh

script: mvn clean compile test cobertura:cobertura

after_success:
  - codecov
  - distribution/deploy.sh

cache:
  directories:
  - $HOME/.m2

notifications:
  email:
    on_success: never
    on_failure: change