language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer
  
before_install:
  - pip install --user codecov
  - "chmod u+x distribution/*.sh"
  - distribution/prepare.sh

script: mvn clean compile test cobertura:cobertura

after_success:
  - codecov
  - distribution/deploy.sh

before_cache:
  - rm -rf $HOME/.m2/repository/fr/landel/utils
  
cache:
  directories:
  - $HOME/.m2