language: java

jdk:
  - oraclejdk8

# to get the latest version of java 8
addons:
  apt:
    packages:
      - oracle-java8-installer
  
before_install:
  - pip install --user codecov
  - curl http://www.jpm4j.org/install/script | sudo sh
  - sudo jpm install com.codacy:codacy-coverage-reporter:assembly
  - "chmod u+x distribution/*.sh"
  - distribution/prepare.sh

script: mvn clean compile test cobertura:cobertura

after_success:
  - codecov
  - codacy-coverage-reporter -l Java -r target/cobertura/coverage.xml
  - distribution/deploy.sh

before_cache:
  - rm -rf $HOME/.m2/repository/fr/landel/utils
  
cache:
  directories:
  - $HOME/.m2