language: java

jdk:
  - oraclejdk8
  
before_install:
  - pip install --user codecov

script: mvn clean compile test cobertura:cobertura

after_success:
  - codecov
  - distribution/sign.sh
  - distribution/deploy.sh

cache:
  directories:
  - $HOME/.m2