language: java

jdk:
  - oraclejdk8
  
install: 
  - "curl https://www.jpm4j.org/install/script | sh"
  - "jpm install com.codacy:codacy-coverage-reporter:assembly"

script: mvn clean compile test

after_success:
  - coveralls
  - coverage xml
  - CODACY_PROJECT_TOKEN=29895bb6d60541cb892b958b8b95b55c codacy-coverage-reporter -l Java -r coverage.xml