language: java

sudo: false

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
    - gnupg2
  
before_install:
  - pip install --user codecov

script: mvn clean compile test cobertura:cobertura

after_success:
  - codecov
  - distribution/deploy.sh

cache:
  directories:
  - $HOME/.m2

notifications:
  email:
    on_success: never
    on_failure: change